name: Riverty CI Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'  # Use the appropriate .NET version for your project

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build 

    - name: Run SpecFlow Tests
      run: dotnet test --logger trx --results-directory TestResults
      env:
         API_BASE_URL: ${{ vars.AUTHORIZATION_KEY }}
         AUTHORIZATION_KEY: ${{ secrets.AUTHORIZATION_KEY }}

    - name: Upload TRX Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: TestResults

    - name: Upload Extent Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: TestResults/ExtentReport.html

